trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: TerraformTaskV1@0
  inputs:
    provider: 'aws'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/awsk8tf/configuration/iaac/aws/kubernetes/'
    backendServiceAWS: 'awstfconn'
    backendAWSBucketName: 'newbucket45678321'
    backendAWSKey: 'myawsk8.tfstate'
